### ISSUE TITLE
design v2

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#23]
https://coding.net/s/8cb1cf8b-23d4-4813-bb22-4f64348d9eab

改变内容：https://github.com/happypeter/book/wiki/design#v2-2018%E5%B9%B42%E6%9C%8822%E6%97%A5

**Comment by happypeter** [comment]
@youngjingwen 只做 css 即可，其他有任何问题反馈给我，我负责修改。

**Comment by happypeter** [comment]
以前已经你已经做好的一部分 css ，有于代码调整，暂时删掉了，从 git 历史中可以找回。

**Comment by youngjingwen** [comment]
@happypeter  老师，css添加了

**Comment by happypeter** [comment]
嗯，非常不错。

有一些细节还是要再调整一下：

- http://localhost:8000/go-responsive 页面的图标是黑白的，通过 css 的 filter gray-scale 来实现

**Comment by happypeter** [comment]
<img width="217" alt="2018-02-25 1 38 10" src="https://user-images.githubusercontent.com/72467/36638473-3790feae-1a31-11e8-995f-ac7f52b76457.png">

这里的白色滚动区域想办法去掉。另外深蓝和浅蓝之间也没有白色的分隔区域。参见设计图。

活跃项目右侧应该显示火焰图标。

**Comment by happypeter** [comment]
图标位置按照设计图调整一下。
<img width="72" alt="2018-02-25 1 42 11" src="https://user-images.githubusercontent.com/72467/36638504-fc90e17e-1a31-11e8-954b-0eb6c5ada61b.png">

**Comment by happypeter** [comment]
header 中，点小猫图标也应该可以返回首页。

**Comment by happypeter** [comment]
http://localhost:8000/go-responsive  页面，也应该显示 footer

**Comment by youngjingwen** [comment]
@happypeter 老师，火焰图标这块 我用 state 控制动态添加图标，总是需要点击两次才添加上图标，setState 是异步执行的。老师 这里还有什么其它方法吗

**Comment by youngjingwen** [comment]
火焰图标写成背景图的话在 activeStyle 控制它的样式效果不是很好

**Comment by happypeter** [comment]
>火焰图标写成背景图的话在 activeStyle 控制它的样式效果不是很好

这个方法我觉得可行。

**Comment by youngjingwen** [comment]
老师，代码已经上传了 您看一下

**Comment by happypeter** [comment]
prefect!
