### ISSUE TITLE
修改 episode 页面的 scroll 策略

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#29]
目前访问 https://book.haoqicat.com/o-o-js/004-es6/#%E7%BB%A7%E6%89%BF 是不能把对应的二级标题显示到页面顶部的。

**Comment by happypeter** [comment]
达成和  https://reactjs.org/docs/components-and-props.html#composing-components 完全一样的效果即可。

**Comment by youngjingwen** [comment]
老师，是修改滚动条的位置吗，使用浏览器的滚动条？

**Comment by happypeter** [comment]
就是达成跟上面链接中一样的效果即可。对，基本上就是使用浏览器的滚动条。

**Comment by youngjingwen** [comment]
@happypeter 老师，代码上传了

**Comment by happypeter** [comment]
基本工作了，但是跟我们需要的效果还是有差别。

**Comment by happypeter** [comment]
如果我浏览器中直接访问：http://localhost:8000/js-monkey/002-loop#%E4%BD%BF%E7%94%A8-break-%E9%80%80%E5%87%BA%E5%BE%AA%E7%8E%AF

那么 `使用 break 退出循环` 这个标题会被 header 盖住。这个是不能满足搜索功能需要的效果的。


### 期待的效果

标题能显示在 header 之下。

**Comment by happypeter** [comment]
@youngjingwen 调整一下吧

**Comment by happypeter** [comment]
参考：https://reactjs.org/docs/accessibility.html#standards-and-guidelines 

打开这个链接，可以看到标题处于 header 之下。

**Comment by youngjingwen** [comment]
上面网站完全加载完成之后，标题还是会被盖住

**Comment by happypeter** [comment]
的确，那么咱们想一个简单方法就行。

把各个标题 `margin-top: 40px` 应该就行，我自己试试哈

**Comment by happypeter** [comment]
margin 不管用

```
  h2 {
    padding: 100px 0 30px;
  }
```

这个管用，但是太难看了。

**Comment by youngjingwen** [comment]
嗯， 我也试了，确实不好看

**Comment by happypeter** [comment]
https://reactjs.org/docs/accessibility.html#wai-aria 这里你再试试，加载完毕了似乎也可以的。

**Comment by youngjingwen** [comment]
多加载一会儿还是会被盖住的，那我再想想办法

**Comment by happypeter** [comment]
加油

**Comment by youngjingwen** [comment]
@happypeter 老师，代码上传了，您看一下

**Comment by happypeter** [comment]
嗯，真是解决了。方法也挺巧妙的。

**Comment by happypeter** [comment]
稍微调整一下，把 `componentWillMount` 改成 `componentDidMount` 或者写成 `constructor` ，因为为了的 react 版本中，willMount 会被删除。

**Comment by happypeter** [comment]
https://github.com/happypeter/book/commit/a70523aba8823911f3ba6dfc537bd85ca1de668c

另外，

```
   const pathContext = this.props.pathContext
```

使用结构赋值的方式来写

```

const {  pathContext  } = this.props
```

**Comment by happypeter** [comment]
<img width="369" alt="2018-03-18 10 51 01" src="https://user-images.githubusercontent.com/72467/37562101-49c6ea38-2a9a-11e8-8da6-f4b258499470.png">

另外就是首页上 网站名 贴 header 太近了。也要调整一下。

**Comment by youngjingwen** [comment]
好的

**Comment by youngjingwen** [comment]
老师，修改好了

**Comment by happypeter** [comment]
好，那咱们这个任务就结束了。等我画下一版的设计图，然后给你发新 issue 。
