### ISSUE TITLE
Design V4

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#34]
#33 也是相关内容。

设计图：https://coding.net/s/d5a5fde8-7e77-478c-b07e-7b09235d0406

补充：https://github.com/happypeter/book/wiki/design#v4-2018%E5%B9%B43%E6%9C%8825%E6%97%A5

**Comment by happypeter** [comment]
https://github.com/happypeter/book/commit/a5dcc24a2a8d3863bfafb597454c90eefd17318e

@youngjingwen 以后可以在写 commit message 的时候添加上 issue 号，例如 `添加色盘颜色 #34` ，这样 push 之后，代码就会自动关联这个 issue 了。

**Comment by youngjingwen** [comment]
好的

**Comment by youngjingwen** [comment]
@happypeter  老师，episode-mobile页面没有书籍目录，还有怎么返回 book-mobile 页面

**Comment by happypeter** [comment]
episode-mobile 上有书名，点书名回到 book-mobile

**Comment by youngjingwen** [comment]
好的👌

**Comment by youngjingwen** [comment]
@happypeter 老师，响应式代码 push 了，您看一下

**Comment by happypeter** [comment]
相关问题，查看 https://github.com/happypeter/book/commit/87818630e66235095efaf9baf6a182925c1d63ee 评论

**Comment by happypeter** [comment]
Logo 相关的警告

>index.js:2177 Warning: Unknown prop `BgFill` on <svg> tag. Remove this prop from the element

未知的属性 `BgFill` 。

**Comment by happypeter** [comment]
原因是

```
<svg width={55} height={41} viewBox="0 0 55 41" {...props}>
```

因为有这一行，那么 BgFill 会直接被传递给 svg 做属性，而同时 BgFill 又不是 svg 的合法属性，所以有这个报错。

**Comment by happypeter** [comment]
@youngjingwen 原则上是这样，svgr 生成的组件，我们是不去动里面的代码的。但是我的 sketch 图中的图标可能有点问题，造成你直接传递 fill 属性，不能改变它的颜色。这个问题，下一版本的设计图中，我会修改一下的。

暂时我手动调整了一下代码。现在 Logo.js 组件工作应该正常了。

**Comment by youngjingwen** [comment]
好的，我知道了

**Comment by happypeter** [comment]
这个任务完成的很棒
