### ISSUE TITLE
代码越长，pre>code 越宽

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#38]
于是手机上的响应式就表现受到影响了。

如果某个页面上有单行很长的代码，那么这个页面的移动版字体就变得很小了。

一个例子：https://book.haoqicat.com/go-responsive/006-patterns

### 期待结果：

代码长了，可以 scroll 。影响总的页面宽度，从而让手机端显示正常。

**Comment by happypeter** [comment]
@youngjingwen 研究一下这个问题。

我自己大致的思路就是：

```js
pre {
  overflow: scroll;
}
```

不过实际上肯定没这么简单。

**Comment by happypeter** [comment]
#34 相关。

**Comment by youngjingwen** [comment]
@happypeter 这部分我修改了一下，pre 里面内容会随这宽度换行，您看一下效果可以吗

**Comment by happypeter** [comment]
嗯，改成换行也挺好。
