### ISSUE TITLE
移动版首页位置错乱

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#40]
<img width="525" alt="2018-03-27 9 35 23" src="https://user-images.githubusercontent.com/72467/37970770-de746354-3206-11e8-896d-afb803219d48.png">

**Comment by youngjingwen** [comment]
嗯，我正在调整

**Comment by youngjingwen** [comment]
@happypeter 这部分代码修改了，另外移动版内容部分添加了滚动条

**Comment by happypeter** [comment]
嗯，现在好了。

**Comment by happypeter** [comment]
嗯，有滚动条体验更佳 👍
