### ISSUE TITLE
文字稿样式

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#41]

**Comment by youngjingwen** [comment]
@happypeter 老师这部分样式我修改了，您看一下效果

**Comment by happypeter** [comment]
效果很赞，一些略微需要调整的地方：

- [x] 二级标题的 `font-weight: normal`
   - 注意是二级标题，不用给三级标题设置任何样式，因为未来我会把文字稿的小标题统一设置为 h2

**Comment by happypeter** [comment]
- [x] 图片是 max-width: 100%; ，而不是 width: 100%
    - 例如：http://localhost:8000/go-responsive/005-viewport 这里的图片如果是 width: 100% 就会被扯的很失真。

**Comment by happypeter** [comment]
- [x] blockquote 字体按照设计图再调整一下把

**Comment by happypeter** [comment]
- [x] ol/ui 都是没有缩进的，参考设计图样式

**Comment by youngjingwen** [comment]
@happypeter 老师，样式调整了

**Comment by happypeter** [comment]
都 OK 了，:dancer:
