### ISSUE TITLE
集成 algolia

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#6]
https://community.algolia.com/docsearch/

实现站内搜索功能。

**Comment by happypeter** [comment]
网站样式参考：https://material-ui-next.com/api/button-base/ 即可，恰好这里也是用 algolia 搜索的。

书稿就临时添加几页测试内容即可。

书稿代码用 Gatsby 来写，书稿要存成纯 markdown 形式。用 graphql 请求书稿，最后编译成静态网站部署到本仓库的 gh-pages 分支。

参考：https://haoqicat.com/gatsby

**Comment by youngjingwen** [comment]
好的

**Comment by happypeter** [comment]
@youngjingwen 基本上就是用咱们熟悉的 gatsby 技术栈，clone 出人家 https://material-ui-next.com/api/button-base/ 这里的效果。

http://reactjs.org/ 用的也是 algolia 和 gatsby 所以可以作为参考资源。

**Comment by happypeter** [comment]
代码直接 push 到这个仓库即可。

**Comment by youngjingwen** [comment]
@happypeter 老师，algolia 这部分我没弄明白，这个任务返回给您吧

**Comment by happypeter** [comment]
@youngjingwen 好，我接着做，你等我视频。

**Comment by happypeter** [comment]
提交了测试网站：http://book.haoqicat.com/ 给 algolia 官方，它们给的回复说这个不是一个文档网站。所以不能用 https://community.algolia.com/docsearch/ 这个服务。

看来网站要先做的有个样子才能提交审核。

**Comment by happypeter** [comment]
或者就不用 docsearch 用 https://www.algolia.com/pricing 这里的免费版

**Comment by happypeter** [comment]
新版上线，再次提交了 https://community.algolia.com/docsearch/ 的审核。

**Comment by happypeter** [comment]
通过之后，我来负责集成即可。

**Comment by happypeter** [comment]
一直没有收到回信，再次提交了信息。

```
Thank you !
We'll review your request shortly, after making sure your website is eligible to DocSearch.

This is a manual process and can take some time.

We'll then email you the code you need to integrate on your website
```

<img width="821" alt="2018-03-05 2 49 17" src="https://user-images.githubusercontent.com/72467/36961018-6bcc2d0c-2084-11e8-98f8-c7156d5b26d1.png">

**Comment by happypeter** [comment]
回复很快呀，说需要插入一段 script ，问我是不是 maintainer 。看来之前几次确实是网络卡，没提交成功。

**Comment by happypeter** [comment]
又给我回复了，让我添加了 https://github.com/happypeter/book/commit/8322c7846bda57c4c38e22e78090eaa367eae387


邮件中有 `selector: //*[@id="___gatsby"]/div/div/div[2]/div[2]` 这样的字眼，看来一旦加上，可能我网站的 div 结构就不能动了。

**Comment by happypeter** [comment]
又回复了：

Please use h1 instead of div:first-child. Update thanks to a PR when it is done pls.

Congratulations, your search is now ready! 
I've successfully configured the underlying crawler and it will now run every 24h. 

You're now a few steps away from having it working on your website: 

- Copy the following CSS/JS snippets and add them to your page 

```
<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
 apiKey: '731d11ffae6b19a7479686c043b7e099', 
 indexName: 'haoqicat', 
 inputSelector: '### REPLACE ME ####', 
 debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 

```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field. 
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/) 
- You can also check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/haoqicat.json). 

Please open a pull request if want to leverage your configuration!

**Comment by happypeter** [comment]
现在工作了，只不过我的二级标题没有 id ，所以跳转不到二级标题位置。

**Comment by happypeter** [comment]
每个 header 都是一个带 id 的 link 了，跟 reactjs.org 学的。

暂时搜索时还用不了，可能要等待下一次爬虫去爬一下才行吧。

**Comment by happypeter** [comment]
嗯，果然现在可以了，点搜索结果，可以指向类似这样的链接了：https://book.haoqicat.com/o-o-js/004-es6/#getters

应该说 algolia 相关的都工作了。对应我自己的界面部分，再调整一下 #29 即可。
