### ISSUE TITLE
设计图 v1

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#8]
用 gatsby 架构来实现。

**Comment by happypeter** [comment]
https://coding.net/s/d5a02c36-946b-4bdf-9678-331142e8ae41

**Comment by youngjingwen** [comment]
@happypeter 老师 页面写的差不多了，代码上传到哪里？

**Comment by happypeter** [comment]
本仓库的 master 分支即可。

**Comment by youngjingwen** [comment]
好的，老师 master分支上原有的东西 删除了是吧

**Comment by happypeter** [comment]
嗯，删了吧

**Comment by happypeter** [comment]
总体上效果不错，有些地方还是需要调整一下，我另外提 issue 了。
