### ISSUE TITLE
样式细节调整

### ISSUE THREAD

**Issue by happypeter** [happypeter/book#9]
继续 #8

**Comment by happypeter** [comment]
### 任务一

header 中的 `图标+好奇猫` 这些内容做成一个连接，指向 `/`

**Comment by happypeter** [comment]
### 任务二

链接的默认颜色应该是设计图上的颜色，不应该是蓝色

**Comment by happypeter** [comment]
### 任务三

首页，每本书上方的吊带没有实现，见设计图

**Comment by happypeter** [comment]
### 任务四

/book 页的图书目录的 hover 效果

**Comment by happypeter** [comment]
@youngjingwen 调整一下上面这些吧

**Comment by youngjingwen** [comment]
好的

**Comment by happypeter** [comment]
看过了，已经都完美修改了。厉害！
